<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>API docs for &ldquo;twisted.python.failure.Failure.__init__&rdquo;</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="method">Method t.p.f.F.__init__(self, exc_value=None, exc_type=None, exc_tb=None):</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.python.html">python</a>.<a href="twisted.python.failure.html">failure</a>.<a href="twisted.python.failure.Failure.html">Failure</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-8.1.0/twisted/python/failure.py#L139">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div><p>Initialize me with an explanation of the error.</p>
<p>By default, this will use the current exception 
(<code>sys.exc_info</code>()). However, if you want to specify a 
particular kind of failure, you can pass an exception as an argument.</p>
If no <code>exc_value</code> is passed, then an &quot;original&quot; 
Failure will be searched for. If the current exception handler that this 
Failure is being constructed in is handling an exception raised by <a 
href="twisted.python.failure.Failure.html#raiseException"><code>raiseException</code></a>, 
then this Failure will act like the original Failure.
<table class="fieldTable"></table></div>
    
    
    <div id="splitTables">
      
      
      
    </div>
    
    
    
    
    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/trac">Twisted</a>, generated by <a href="http://codespeak.net/~mwh/pydoctor/">pydoctor</a> at 2008-05-18 16:50:21.
    </address>
  </body>
</html>