<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>twisted.python.failure.Failure.trap : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="method">t.p.f.F.trap(self, *errorTypes) : method documentation</h1>
    <p>
      <span id="part">Part of <a href="twisted.html">twisted</a>.<a href="twisted.python.html">python</a>.<a href="twisted.python.failure.html">failure</a>.<a href="twisted.python.failure.Failure.html">Failure</a></span>
      <a href="http://twistedmatrix.com/trac/browser/tags/releases/twisted-10.0.0//twisted/python/failure.py#L278">View Source</a>
      
    </p>
    <div>
      
    </div>
    <div><p>Trap this failure if its type is in a predetermined list.</p>
<p>This allows you to trap a Failure in an error callback.  It will be 
automatically re-raised if it is not a type that you expect.</p>
The reason for having this particular API is because it's very useful in
Deferred errback chains:
<pre class="literalblock">
   def _ebFoo(self, failure):
       r = failure.trap(Spam, Eggs)
       print 'The Failure is due to either Spam or Eggs!'
       if r == Spam:
           print 'Spam did it!'
       elif r == Eggs:
           print 'Eggs did it!'
</pre>
If the failure is not a Spam or an Eggs, then the Failure will be 
'passed on' to the next errback.
<table class="fieldTable"><tr class="fieldStart"><td class="fieldName">Parameters</td><td class="fieldArg">errorTypes</td><td> (type: <code>Exception</code>
)</td></tr></table></div>

    
    
    <div id="splitTables">
      
      
      
    </div>
    
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="http://twistedmatrix.com/">Twisted</a>, generated by <a href="http://codespeak.net/~mwh/pydoctor/">pydoctor</a> at 2010-03-06 12:41:43.
    </address>
  </body>
</html>